apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apis.apps.tanzu.vmware.com/register-api: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location: 
        path: "/swagger"
      owner: weather-department
      system: weather
      description: Weather report management
  source:
    git:
      url: https://github.com/cdelashmutt-pivotal/weatherforecast-steeltoe
      ref:
        branch: main
